In [1]:
'''
-data analysis
- data cleaning
- feature engineering
- file handling
'''

'\n-data analysis\n- data cleaning\n- feature engineering\n- file handling\n'

In [2]:
# 1d -> series
# 2d -> DataFrame
import pandas as pd

In [6]:
numbers = pd.Series([1,2,3,4,5,6,7,8])
numbers

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [ ]:
'''
loc -> location -> Slice data through alphabetical index.
iloc -> Integer location -> Slice data through numerical index
'''

In [7]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}, index=["a", "b", "c"])

print(df)

      Name  Age
a    Alice   25
b      Bob   30
c  Charlie   35

In [14]:
df.loc["a"]

Name    Alice
Age        25
Name: a, dtype: object

In [15]:
df.iloc[1]

Name    Bob
Age      30
Name: b, dtype: object

In [13]:
df = pd.ExcelFile(r'EMPLOYEES.xlsx')
df_data = df.parse()

In [15]:
emp_salary = df_data[(df_data['SALARY'] > 100000) | (df_data['SALARY'] < 18000)][['FIRST_NAME', 'LAST_NAME', 'HIRE_DATE', 'SALARY']].head()
emp_salary

  FIRST_NAME LAST_NAME            HIRE_DATE  SALARY
1      Neena   Kochhar  21.09.2005 00:00:00   17000
2        Lex   De Haan  13.01.2001 00:00:00   17000
3  Alexander    Hunold  03.01.2006 00:00:00    9000
4      Bruce     Ernst  21.05.2007 00:00:00    6000
5      David    Austin  25.06.2005 00:00:00    4800

In [17]:
emp_salary_bet = df_data[(df_data['SALARY']).between(10000,18000)]
emp_salary_bet

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,17.08.2002 00:00:00,FI_MGR,12008,NaN,101.0,100.0
14,114,Den,Raphaely,DRAPHEAL,515.127.4561,07.12.2002 00:00:00,PU_MAN,11000,NaN,100.0,30.0
45,145,John,Russell,JRUSSEL,011.44.1344.429268,01.10.2004 00:00:00,SA_MAN,14000,0.40,100.0,80.0
46,146,Karen,Partners,KPARTNER,011.44.1344.467268,05.01.2005 00:00:00,SA_MAN,13500,0.30,100.0,80.0
47,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,10.03.2005 00:00:00,SA_MAN,12000,0.30,100.0,80.0
48,148,Gerald,Cambrault,GCAMBRAU,011.44.1344.619268,15.10.2007 00:00:00,SA_MAN,11000,0.30,100.0,80.0
49,149,Eleni,Zlotkey,EZLOTKEY,011.44.1344.429018,29.01.2008 00:00:00,SA_MAN,10500,0.20,100.0,80.0
50,150,Peter,Tucker,PTUCKER,011.44.1344.129268,30.01.2005 00:00:00,SA_REP,10000,0.30,145.0,80.0
56,156,Janette,King,JKING,011.44.1345.429268,30.01.2004 00:00:00,SA_REP,10000,0.35,146.0,80.0
62,162,Clara,Vishney,CVISHNEY,011.44.1346.129268,11.11.2005 00:00:00,SA_REP,10500,0.25,147.0,80.0
68,168,Lisa,Ozer,LOZER,011.44.1343.929268,11.03.2005 00:00:00,SA_REP,11500,0.25,148.0,80.0
69,169,Harrison,Bloom,HBLOOM,011.44.1343.829268,23.03.2006 00:00:00,SA_REP,10000,0.20,148.0,80.0
74,174,Ellen,Abel,EABEL,011.44.1644.429267,11.05.2004 00:00:00,SA_REP,11000,0.30,149.0,80.0
101,201,Michael,Hartstein,MHARTSTE,515.123.5555,17.02.2004 00:00:00,MK_MAN,13000,NaN,100.0,20.0
104,204,Hermann,Baer,HBAER,515.123.8888,07.06.2002 00:00:00,PR_REP,10000,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0
108,204,Hermann,Baer,HBAER,515.123.8888,07.06.2002 00:00:00,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0

In [20]:
# find employees details who works in job AD_VP and IT_PROG
emp_job = df_data[(df_data['JOB_ID'] == 'AD_VP') | (df_data['JOB_ID'] == 'IT_PROG')]
emp_job

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,21.05.2007 00:00:00,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,25.06.2005 00:00:00,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,05.02.2006 00:00:00,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,07.02.2007 00:00:00,IT_PROG,4200,NaN,103.0,60.0

In [22]:
emp_job_in = df_data[df_data['JOB_ID'].isin(['AD_VP','IT_PROG'])]
emp_job_in

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,21.05.2007 00:00:00,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,25.06.2005 00:00:00,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,05.02.2006 00:00:00,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,07.02.2007 00:00:00,IT_PROG,4200,NaN,103.0,60.0

In [23]:
#find employee details who earns more than 8000 and works in department 70 or 60

In [25]:
emp_details = df_data[(df_data['SALARY'] > 8000) & ((df_data['DEPARTMENT_ID'] == 60) | (df_data['DEPARTMENT_ID'] == 70))]
emp_details

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
104,204,Hermann,Baer,HBAER,515.123.8888,07.06.2002 00:00:00,PR_REP,10000,NaN,101.0,70.0
108,204,Hermann,Baer,HBAER,515.123.8888,07.06.2002 00:00:00,PR_REP,10000,NaN,101.0,70.0

In [26]:
emp_details = df_data[(df_data['SALARY'] > 8000) & (df_data['DEPARTMENT_ID'].isin([60, 70]))]
emp_details

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
104,204,Hermann,Baer,HBAER,515.123.8888,07.06.2002 00:00:00,PR_REP,10000,NaN,101.0,70.0
108,204,Hermann,Baer,HBAER,515.123.8888,07.06.2002 00:00:00,PR_REP,10000,NaN,101.0,70.0

In [27]:
#1. single boolean condition
df_data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,17.06.2003 00:00:00,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,21.05.2007 00:00:00,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,07.06.2002 00:00:00,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,07.06.2002 00:00:00,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,07.06.2002 00:00:00,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,07.06.2002 00:00:00,AC_ACCOUNT,8300,NaN,205.0,110.0