In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('dataset/cleaned_data.csv')

In [4]:
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22,LinkedIn,Exceeds,4.60,5,0,2019-01-17,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4,Indeed,Fully Meets,4.96,3,6,2016-02-24,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20,LinkedIn,Fully Meets,3.02,3,0,2012-05-15,0,3
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16,Indeed,Fully Meets,4.84,5,0,2019-01-03,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39,Google Search,Fully Meets,5.00,4,0,2016-02-01,0,2

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    object
 16  Gender                      311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    object
 22  DateofTermination           104 non-null    object
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   311 non-null    int64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    object
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
dtypes: float64(1), int64(17), object(18)
memory usage: 87.6+ KB

In [6]:
# find total employees working in departments
df['Department'].value_counts()

Department
Production              209
IT/IS                    50
Sales                    31
Software Engineering     11
Admin Offices             9
Executive Office          1
Name: count, dtype: int64

In [7]:
# when using group by must use aggregate but if u use aggregate not neccessaily use aggregate.

## Aggregate Function -> KPI -> Key Performance Indicator('mean','max','min','count') -> KPI making data to be seen in summmary.

## group by (categorical) + aggregate function (Categorical, Discrete,continous) -> Analysis
'''
for continuous use  --> avg, max, min but not count
for discrete --> count,max , min , sum but not mean
'''

'\nfor continuous use  --> avg, max, min but not count\nfor discrete --> count,max , min , sum but not mean\n'

In [8]:
emp_dep = df.groupby('Department')['EmpID'].count().reset_index().rename(
    columns = {'EmpID' : 'Total Employees'}
).sort_values(ascending = False, by = 'Total Employees' , ignore_index = True)
emp_dep

             Department  Total Employees
0            Production              209
1                 IT/IS               50
2                 Sales               31
3  Software Engineering               11
4         Admin Offices                9
5      Executive Office                1

In [9]:
emp_dep = df.groupby('Department')['EmpID'].count().rename('Total_Employees').sort_values(ascending =False)

format_data =  emp_dep.to_markdown(numalign ='center', stralign = 'center')
print(format_data)

|      Department      |  Total_Employees  |
|:--------------------:|:-----------------:|
|      Production      |        209        |
|        IT/IS         |        50         |
|        Sales         |        31         |
| Software Engineering |        11         |
|    Admin Offices     |         9         |
|   Executive Office   |         1         |

In [10]:
# Find total salary distribution to each employee by their job_position.
t_sal = df.groupby('Position')['Salary'].sum().reset_index().sort_values(ascending = False , by = 'Salary'
                                                                        ,ignore_index = True)
t_sal['Salary'] = t_sal['Salary'].map("Rs.{:,.2f}".format)
format_t = t_sal.to_markdown(numalign='center', stralign='center')

print(format_t)

|    |           Position           |     Salary      |
|:--:|:----------------------------:|:---------------:|
| 0  |   Production Technician I    | Rs.7,606,812.00 |
| 1  |   Production Technician II   | Rs.3,698,856.00 |
| 2  |      Area Sales Manager      | Rs.1,753,179.00 |
| 3  |      Production Manager      | Rs.1,054,123.00 |
| 4  |      Software Engineer       |  Rs.967,192.00  |
| 5  |         Data Analyst         |  Rs.718,055.00  |
| 6  |    Database Administrator    |  Rs.542,498.00  |
| 7  |          IT Support          |  Rs.509,475.00  |
| 8  |     Sr. Network Engineer     |  Rs.465,354.00  |
| 9  |         BI Developer         |  Rs.381,860.00  |
| 10 |       Network Engineer       |  Rs.308,025.00  |
| 11 |       IT Manager - DB        |  Rs.289,919.00  |
| 12 |     Senior BI Developer      |  Rs.254,408.00  |
| 13 |       President & CEO        |  Rs.250,000.00  |
| 14 |             CIO              |  Rs.220,450.00  |
| 15 |        Sales Manager         |  Rs.207,720.00  |
| 16 |        Sr. Accountant        |  Rs.205,718.00  |
| 17 |           Sr. DBA            |  Rs.204,468.00  |
| 18 |         Accountant I         |  Rs.190,523.00  |
| 19 |      Director of Sales       |  Rs.180,000.00  |
| 20 |         IT Director          |  Rs.178,000.00  |
| 21 |    Director of Operations    |  Rs.170,500.00  |
| 22 |      IT Manager - Infra      |  Rs.157,000.00  |
| 23 |   Administrative Assistant   |  Rs.156,840.00  |
| 24 |        Data Architect        |  Rs.150,290.00  |
| 25 |     IT Manager - Support     |  Rs.138,888.00  |
| 26 |   Principal Data Architect   |  Rs.120,000.00  |
| 27 |         BI Director          |  Rs.110,929.00  |
| 28 |     Enterprise Architect     |  Rs.103,613.00  |
| 29 |   Shared Services Manager    |  Rs.93,046.00   |
| 30 | Software Engineering Manager |  Rs.77,692.00   |

In [11]:
def currencyConverter(dataframe, prefix, *args):
    for col in args:
        dataframe[col] = dataframe[col].map(f'{prefix}'"{:,.2f}".format)

In [12]:
emp_pos_details = df.groupby('Position').agg(
    Total_Salary = ('Salary', 'sum'),
    Total_Employees = ('EmpID', 'count'),
    Max_Salary = ('Salary', 'max'),
    Min_Salary = ('Salary', 'min'),
    Avg_Salary = ('Salary', 'mean')
).reset_index()

emp_pos_details.columns = emp_pos_details.columns.str.replace('_', ' ') 

currencyConverter(emp_pos_details, 'Rs.', 'Total Salary', 'Max Salary','Min Salary', 'Avg Salary')

emp_pos_details

,Position,Total Salary,Total Employees,Max Salary,Min Salary,Avg Salary
0,Accountant I,"Rs.190,523.00",3,"Rs.64,520.00","Rs.63,000.00","Rs.63,507.67"
1,Administrative Assistant,"Rs.156,840.00",3,"Rs.55,000.00","Rs.49,920.00","Rs.52,280.00"
2,Area Sales Manager,"Rs.1,753,179.00",27,"Rs.74,326.00","Rs.55,875.00","Rs.64,932.56"
3,BI Developer,"Rs.381,860.00",4,"Rs.99,020.00","Rs.90,100.00","Rs.95,465.00"
4,BI Director,"Rs.110,929.00",1,"Rs.110,929.00","Rs.110,929.00","Rs.110,929.00"
5,CIO,"Rs.220,450.00",1,"Rs.220,450.00","Rs.220,450.00","Rs.220,450.00"
6,Data Analyst,"Rs.718,055.00",8,"Rs.93,554.00","Rs.83,552.00","Rs.89,756.88"
7,Data Architect,"Rs.150,290.00",1,"Rs.150,290.00","Rs.150,290.00","Rs.150,290.00"
8,Database Administrator,"Rs.542,498.00",5,"Rs.114,800.00","Rs.97,999.00","Rs.108,499.60"
9,Director of Operations,"Rs.170,500.00",1,"Rs.170,500.00","Rs.170,500.00","Rs.170,500.00"
10,Director of Sales,"Rs.180,000.00",1,"Rs.180,000.00","Rs.180,000.00","Rs.180,000.00"
11,Enterprise Architect,"Rs.103,613.00",1,"Rs.103,613.00","Rs.103,613.00","Rs.103,613.00"
12,IT Director,"Rs.178,000.00",1,"Rs.178,000.00","Rs.178,000.00","Rs.178,000.00"
13,IT Manager - DB,"Rs.289,919.00",2,"Rs.148,999.00","Rs.140,920.00","Rs.144,959.50"
14,IT Manager - Infra,"Rs.157,000.00",1,"Rs.157,000.00","Rs.157,000.00","Rs.157,000.00"
15,IT Manager - Support,"Rs.138,888.00",1,"Rs.138,888.00","Rs.138,888.00","Rs.138,888.00"
16,IT Support,"Rs.509,475.00",8,"Rs.74,679.00","Rs.50,178.00","Rs.63,684.38"
17,Network Engineer,"Rs.308,025.00",5,"Rs.76,029.00","Rs.50,750.00","Rs.61,605.00"
18,President & CEO,"Rs.250,000.00",1,"Rs.250,000.00","Rs.250,000.00","Rs.250,000.00"
19,Principal Data Architect,"Rs.120,000.00",1,"Rs.120,000.00","Rs.120,000.00","Rs.120,000.00"
20,Production Manager,"Rs.1,054,123.00",14,"Rs.88,976.00","Rs.62,957.00","Rs.75,294.50"
21,Production Technician I,"Rs.7,606,812.00",137,"Rs.64,991.00","Rs.45,046.00","Rs.55,524.18"
22,Production Technician II,"Rs.3,698,856.00",57,"Rs.74,813.00","Rs.55,315.00","Rs.64,892.21"
23,Sales Manager,"Rs.207,720.00",3,"Rs.72,992.00","Rs.65,729.00","Rs.69,240.00"
24,Senior BI Developer,"Rs.254,408.00",3,"Rs.87,921.00","Rs.81,584.00","Rs.84,802.67"
25,Shared Services Manager,"Rs.93,046.00",1,"Rs.93,046.00","Rs.93,046.00","Rs.93,046.00"
26,Software Engineer,"Rs.967,192.00",10,"Rs.108,987.00","Rs.83,363.00","Rs.96,719.20"
27,Software Engineering Manager,"Rs.77,692.00",1,"Rs.77,692.00","Rs.77,692.00","Rs.77,692.00"
28,Sr. Accountant,"Rs.205,718.00",2,"Rs.106,367.00","Rs.99,351.00","Rs.102,859.00"
29,Sr. DBA,"Rs.204,468.00",2,"Rs.104,437.00","Rs.100,031.00","Rs.102,234.00"
30,Sr. Network Engineer,"Rs.465,354.00",5,"Rs.107,226.00","Rs.85,028.00","Rs.93,070.80"

In [13]:
def convertDateTime(dataframe , *args):
    for col in args:
        dataframe[col] = pd.to_datetime(dataframe[col], format='mixed')

In [14]:
convertDateTime(df, 'DOB','DateofHire','DateofTermination','LastPerformanceReview_Date')

In [15]:
df['HireYear'] = df['DateofHire'].dt.year
df['HireMonth'] = df['DateofHire'].dt.month
df['HireDay']= df['DateofHire'].dt.day

In [16]:
df['HireMonthName'] = df['DateofHire'].dt.month_name()
df['HireDayName'] = df['DateofHire'].dt.day_name()

In [17]:
# Find total employees hired in each different year

In [18]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences', 'HireYear', 'HireMonth', 'HireDay', 'HireMonthName',
       'HireDayName'],
      dtype='object')

In [19]:
emp_year = df.groupby('HireYear')['EmpID'].count().reset_index().rename(
    columns={'HireYear': 'Hire Year', 'EmpID': 'Total Employees'}
)
emp_year['Hire_PCT_YOY'] = (emp_year['Total Employees'].pct_change().fillna(0)) * 100
emp_year['Hire_PCT_YOY'] = emp_year['Hire_PCT_YOY'].map('{:,.2f}%'.format)
emp_year

    Hire Year  Total Employees Hire_PCT_YOY
0        2006                1        0.00%
1        2007                2      100.00%
2        2008                3       50.00%
3        2009                7      133.33%
4        2010                9       28.57%
5        2011               83      822.22%
6        2012               45      -45.78%
7        2013               44       -2.22%
8        2014               60       36.36%
9        2015               36      -40.00%
10       2016               14      -61.11%
11       2017                6      -57.14%
12       2018                1      -83.33%

In [21]:
month_emp = df.groupby(['HireMonth','HireMonthName'])['EmpID'].count().reset_index()[['HireMonthName','EmpID']]
month_emp

   HireMonthName  EmpID
0        January     54
1       February     31
2          March     19
3          April     27
4            May     33
5           June      8
6           July     44
7         August     20
8      September     39
9        October      7
10      November     28
11      December      1

In [24]:
day_dict ={
    'Sunday' :1,
    'Monday' : 2,
    'Tuesday' : 3,
    'Wednesday' : 4,
    'Thursday' : 5,
    'Friday' : 6,
    'Saturday' : 7,
}
df['day_dict'] = df['HireDayName'].map(day_dict)

In [29]:
day_name = (df.groupby(['day_dict','HireDayName'])['EmpID']
            .count()
            .reset_index()
            [['HireDayName','EmpID']])
day_name

  HireDayName  EmpID
0      Sunday      6
1      Monday    259
2     Tuesday     19
3   Wednesday      9
4    Thursday      9
5      Friday      6
6    Saturday      3

In [55]:
# find total employees and their salary distributed by each departments and its martial description

emp_details = df.groupby(['Department', 'MaritalDesc']).agg(
    Total_Employees = ('EmpID','count'),
    Total_Salary = ('Salary','sum')
).reset_index()
emp_details

              Department MaritalDesc  Total_Employees  Total_Salary
0          Admin Offices    Divorced                1         64520
1          Admin Offices     Married                6        466684
2          Admin Offices      Single                2        114923
3       Executive Office     Married                1        250000
4                  IT/IS    Divorced                4        380032
5                  IT/IS     Married               23       2057364
6                  IT/IS   Separated                1         61242
7                  IT/IS      Single               21       2247368
8                  IT/IS     Widowed                1        107226
9             Production    Divorced               24       1415276
10            Production     Married               81       4857478
11            Production   Separated                9        559105
12            Production      Single               89       5343467
13            Production     Widowed                6        354965
14                 Sales    Divorced                1         72992
15                 Sales     Married               10        758254
16                 Sales   Separated                2        134865
17                 Sales      Single               17       1115418
18                 Sales     Widowed                1         59370
19  Software Engineering     Married                3        268857
20  Software Engineering      Single                8        776027

In [51]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences', 'HireYear', 'HireMonth', 'HireDay', 'HireMonthName',
       'HireDayName', 'day_dict'],
      dtype='object')