In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Employees.csv')
df.head()

In [3]:
df.info()

In [4]:
# to check number of null value in each column
df.isnull().sum()

In [19]:
# df.dropna() # this is temporory change , but for permanent change always use inplace = True

# dropna(axis = 0(default)/1 , how = 'any'(default)/'all' , inplace = True/False(default))

# how = any  -> any 1 null value , it will remove whole column.
# how  = all -> have to be all null value to get removed.



df.dropna(how = 'all', inplace =True)
df

In [20]:
df = df.dropna() # no need to keep inplace here
df.head()

In [21]:
''' to drop specific columns

drop(columns = [columns_name])
'''
'''
df = df.drop(columns = ['SALARY','JOB_ID'])
df.head()
'''

# fill data

In [13]:
df.isnull().sum()

In [14]:
# commission percentage
com_mean = round(df['COMMISSION_PCT'].mean(),2)
com_median = df['COMMISSION_PCT'].median()

print (com_mean)
print (com_median)

In [15]:
df['COMMISSION_PCT'].skew()

In [17]:
# df['COMMISSION_PCT'].fillna(com_mean, inplace = True) OR

df.fillna({'COMMISSION_PCT' : com_mean}, inplace = True)

In [18]:
df

In [19]:
mgr_mode = df['MANAGER_ID'].mode()[0]
dep_mode = df['DEPARTMENT_ID'].mode()[0]

In [20]:
print(mgr_mode)

145.0

In [21]:
print(dep_mode)

80.0

In [22]:
df.fillna({'MANAGER_ID' : mgr_mode}, inplace = True)
df.fillna({'DEPARTMENT_ID' : dep_mode}, inplace = True)

In [15]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
45,145,John,Russell,JRUSSEL,011.44.1344.429268,10/1/2004,SA_MAN,14000,0.40,100.0,80.0
46,146,Karen,Partners,KPARTNER,011.44.1344.467268,1/5/2005,SA_MAN,13500,0.30,100.0,80.0
47,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,3/10/2005,SA_MAN,12000,0.30,100.0,80.0
48,148,Gerald,Cambrault,GCAMBRAU,011.44.1344.619268,10/15/2007,SA_MAN,11000,0.30,100.0,80.0
49,149,Eleni,Zlotkey,EZLOTKEY,011.44.1344.429018,1/29/2008,SA_MAN,10500,0.20,100.0,80.0
50,150,Peter,Tucker,PTUCKER,011.44.1344.129268,1/30/2005,SA_REP,10000,0.30,145.0,80.0
51,151,David,Bernstein,DBERNSTE,011.44.1344.345268,3/24/2005,SA_REP,9500,0.25,145.0,80.0
52,152,Peter,Hall,PHALL,011.44.1344.478968,8/20/2005,SA_REP,9000,0.25,145.0,80.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,3/30/2006,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,12/9/2006,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,11/23/2007,SA_REP,7000,0.15,145.0,80.0
56,156,Janette,King,JKING,011.44.1345.429268,1/30/2004,SA_REP,10000,0.35,146.0,80.0
57,157,Patrick,Sully,PSULLY,011.44.1345.929268,3/4/2004,SA_REP,9500,0.35,146.0,80.0
58,158,Allan,McEwen,AMCEWEN,011.44.1345.829268,8/1/2004,SA_REP,9000,0.35,146.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,3/10/2005,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,12/15/2005,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,11/3/2006,SA_REP,7000,0.25,146.0,80.0
62,162,Clara,Vishney,CVISHNEY,011.44.1346.129268,11/11/2005,SA_REP,10500,0.25,147.0,80.0
63,163,Danielle,Greene,DGREENE,011.44.1346.229268,3/19/2007,SA_REP,9500,0.15,147.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,1/24/2008,SA_REP,7200,0.10,147.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,2/23/2008,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,3/24/2008,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,4/21/2008,SA_REP,6200,0.10,147.0,80.0
68,168,Lisa,Ozer,LOZER,011.44.1343.929268,3/11/2005,SA_REP,11500,0.25,148.0,80.0
69,169,Harrison,Bloom,HBLOOM,011.44.1343.829268,3/23/2006,SA_REP,10000,0.20,148.0,80.0
70,170,Tayler,Fox,TFOX,011.44.1343.729268,1/24/2006,SA_REP,9600,0.20,148.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,2/23/2007,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,3/24/2007,SA_REP,7300,0.15,148.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,4/21/2008,SA_REP,6100,0.10,148.0,80.0
74,174,Ellen,Abel,EABEL,011.44.1644.429267,5/11/2004,SA_REP,11000,0.30,149.0,80.0
75,175,Alyssa,Hutton,AHUTTON,011.44.1644.429266,3/19/2005,SA_REP,8800,0.25,149.0,80.0
76,176,Jonathon,Taylor,JTAYLOR,011.44.1644.429265,3/24/2006,SA_REP,8600,0.20,149.0,80.0
77,177,Jack,Livingston,JLIVINGS,011.44.1644.429264,4/23/2006,SA_REP,8400,0.20,149.0,80.0
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,1/4/2008,SA_REP,6200,0.10,149.0,80.0

In [16]:
df['MANAGER_ID'].unique()

array([100., 145., 146., 147., 148., 149.])

In [17]:
df['DEPARTMENT_ID'].unique()

array([80.])

In [23]:

df.fillna({'MANAGER__ID' : 0})
df.fillna({'DEPARTMENT_ID' : 0})
df.fillna({'COMMISSION_PCT' : 0})

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
45,145,John,Russell,JRUSSEL,011.44.1344.429268,10/1/2004,SA_MAN,14000,0.40,100.0,80.0
46,146,Karen,Partners,KPARTNER,011.44.1344.467268,1/5/2005,SA_MAN,13500,0.30,100.0,80.0
47,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,3/10/2005,SA_MAN,12000,0.30,100.0,80.0
48,148,Gerald,Cambrault,GCAMBRAU,011.44.1344.619268,10/15/2007,SA_MAN,11000,0.30,100.0,80.0
49,149,Eleni,Zlotkey,EZLOTKEY,011.44.1344.429018,1/29/2008,SA_MAN,10500,0.20,100.0,80.0
50,150,Peter,Tucker,PTUCKER,011.44.1344.129268,1/30/2005,SA_REP,10000,0.30,145.0,80.0
51,151,David,Bernstein,DBERNSTE,011.44.1344.345268,3/24/2005,SA_REP,9500,0.25,145.0,80.0
52,152,Peter,Hall,PHALL,011.44.1344.478968,8/20/2005,SA_REP,9000,0.25,145.0,80.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,3/30/2006,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,12/9/2006,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,11/23/2007,SA_REP,7000,0.15,145.0,80.0
56,156,Janette,King,JKING,011.44.1345.429268,1/30/2004,SA_REP,10000,0.35,146.0,80.0
57,157,Patrick,Sully,PSULLY,011.44.1345.929268,3/4/2004,SA_REP,9500,0.35,146.0,80.0
58,158,Allan,McEwen,AMCEWEN,011.44.1345.829268,8/1/2004,SA_REP,9000,0.35,146.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,3/10/2005,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,12/15/2005,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,11/3/2006,SA_REP,7000,0.25,146.0,80.0
62,162,Clara,Vishney,CVISHNEY,011.44.1346.129268,11/11/2005,SA_REP,10500,0.25,147.0,80.0
63,163,Danielle,Greene,DGREENE,011.44.1346.229268,3/19/2007,SA_REP,9500,0.15,147.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,1/24/2008,SA_REP,7200,0.10,147.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,2/23/2008,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,3/24/2008,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,4/21/2008,SA_REP,6200,0.10,147.0,80.0
68,168,Lisa,Ozer,LOZER,011.44.1343.929268,3/11/2005,SA_REP,11500,0.25,148.0,80.0
69,169,Harrison,Bloom,HBLOOM,011.44.1343.829268,3/23/2006,SA_REP,10000,0.20,148.0,80.0
70,170,Tayler,Fox,TFOX,011.44.1343.729268,1/24/2006,SA_REP,9600,0.20,148.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,2/23/2007,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,3/24/2007,SA_REP,7300,0.15,148.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,4/21/2008,SA_REP,6100,0.10,148.0,80.0
74,174,Ellen,Abel,EABEL,011.44.1644.429267,5/11/2004,SA_REP,11000,0.30,149.0,80.0
75,175,Alyssa,Hutton,AHUTTON,011.44.1644.429266,3/19/2005,SA_REP,8800,0.25,149.0,80.0
76,176,Jonathon,Taylor,JTAYLOR,011.44.1644.429265,3/24/2006,SA_REP,8600,0.20,149.0,80.0
77,177,Jack,Livingston,JLIVINGS,011.44.1644.429264,4/23/2006,SA_REP,8400,0.20,149.0,80.0
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,1/4/2008,SA_REP,6200,0.10,149.0,80.0

In [24]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
45,145,John,Russell,JRUSSEL,011.44.1344.429268,10/1/2004,SA_MAN,14000,0.40,100.0,80.0
46,146,Karen,Partners,KPARTNER,011.44.1344.467268,1/5/2005,SA_MAN,13500,0.30,100.0,80.0
47,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,3/10/2005,SA_MAN,12000,0.30,100.0,80.0
48,148,Gerald,Cambrault,GCAMBRAU,011.44.1344.619268,10/15/2007,SA_MAN,11000,0.30,100.0,80.0
49,149,Eleni,Zlotkey,EZLOTKEY,011.44.1344.429018,1/29/2008,SA_MAN,10500,0.20,100.0,80.0
50,150,Peter,Tucker,PTUCKER,011.44.1344.129268,1/30/2005,SA_REP,10000,0.30,145.0,80.0
51,151,David,Bernstein,DBERNSTE,011.44.1344.345268,3/24/2005,SA_REP,9500,0.25,145.0,80.0
52,152,Peter,Hall,PHALL,011.44.1344.478968,8/20/2005,SA_REP,9000,0.25,145.0,80.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,3/30/2006,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,12/9/2006,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,11/23/2007,SA_REP,7000,0.15,145.0,80.0
56,156,Janette,King,JKING,011.44.1345.429268,1/30/2004,SA_REP,10000,0.35,146.0,80.0
57,157,Patrick,Sully,PSULLY,011.44.1345.929268,3/4/2004,SA_REP,9500,0.35,146.0,80.0
58,158,Allan,McEwen,AMCEWEN,011.44.1345.829268,8/1/2004,SA_REP,9000,0.35,146.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,3/10/2005,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,12/15/2005,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,11/3/2006,SA_REP,7000,0.25,146.0,80.0
62,162,Clara,Vishney,CVISHNEY,011.44.1346.129268,11/11/2005,SA_REP,10500,0.25,147.0,80.0
63,163,Danielle,Greene,DGREENE,011.44.1346.229268,3/19/2007,SA_REP,9500,0.15,147.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,1/24/2008,SA_REP,7200,0.10,147.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,2/23/2008,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,3/24/2008,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,4/21/2008,SA_REP,6200,0.10,147.0,80.0
68,168,Lisa,Ozer,LOZER,011.44.1343.929268,3/11/2005,SA_REP,11500,0.25,148.0,80.0
69,169,Harrison,Bloom,HBLOOM,011.44.1343.829268,3/23/2006,SA_REP,10000,0.20,148.0,80.0
70,170,Tayler,Fox,TFOX,011.44.1343.729268,1/24/2006,SA_REP,9600,0.20,148.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,2/23/2007,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,3/24/2007,SA_REP,7300,0.15,148.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,4/21/2008,SA_REP,6100,0.10,148.0,80.0
74,174,Ellen,Abel,EABEL,011.44.1644.429267,5/11/2004,SA_REP,11000,0.30,149.0,80.0
75,175,Alyssa,Hutton,AHUTTON,011.44.1644.429266,3/19/2005,SA_REP,8800,0.25,149.0,80.0
76,176,Jonathon,Taylor,JTAYLOR,011.44.1644.429265,3/24/2006,SA_REP,8600,0.20,149.0,80.0
77,177,Jack,Livingston,JLIVINGS,011.44.1644.429264,4/23/2006,SA_REP,8400,0.20,149.0,80.0
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,1/4/2008,SA_REP,6200,0.10,149.0,80.0

In [23]:
df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     0
dtype: int64