In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataset/HR_Dataset Refresh.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              582 non-null    object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    object
 22  DateofTermination           196 non-null    object
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 163.8+ KB

In [4]:
def convertDateTime(dataframe , *args):
    for col in args:
        dataframe[col] = pd.to_datetime(dataframe[col], format='mixed')

In [5]:
convertDateTime(df, 'DOB','DateofHire','DateofTermination','LastPerformanceReview_Date')

In [6]:
df['HireYear'] = df['DateofHire'].dt.year
df['HireMonth'] = df['DateofHire'].dt.month
df['HireDay']= df['DateofHire'].dt.day

In [7]:
df['HireMonthName'] = df['DateofHire'].dt.month_name()
df['HireDayName'] = df['DateofHire'].dt.day_name()

In [8]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,HireYear,HireMonth,HireDay,HireMonthName,HireDayName
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,5,0,2019-01-17,0,1,2011,7,5,July,Tuesday
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,3,6,2016-02-24,0,17,2015,3,30,March,Monday
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,3,0,2012-05-15,0,3,2011,7,5,July,Tuesday
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,5,0,2019-01-03,0,15,2008,1,7,January,Monday
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,4,0,2016-02-01,0,2,2011,7,11,July,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,4,0,2016-02-01,0,2,2011,7,11,July,Monday
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,5,0,2019-01-07,0,15,2012,1,9,January,Monday
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,3,4,2019-01-02,0,19,2014,11,10,November,Monday
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,4,0,2019-02-25,0,19,2013,9,30,September,Monday
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,3,0,2019-01-25,0,4,2009,7,6,July,Monday

In [9]:
df['Salary'].max(0)

650000

In [10]:
def salaryLabel(salary):
    if salary <= 70000:
        return 'low salary'
    elif salary > 70000 and salary <= 150000:
        return 'average Salary'
    elif salary > 150000:
        return 'high salary'
    else:  
        return 'Invalid Salary'

In [11]:
df['SalaryLabel'] = df['Salary'].apply(salaryLabel)

In [12]:
df['SalaryLabel'].value_counts()

SalaryLabel
low salary        427
average Salary    142
high salary        13
Name: count, dtype: int64

In [13]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,HireYear,HireMonth,HireDay,HireMonthName,HireDayName,SalaryLabel
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,0,2019-01-17,0,1,2011,7,5,July,Tuesday,low salary
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,6,2016-02-24,0,17,2015,3,30,March,Monday,average Salary
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,0,2012-05-15,0,3,2011,7,5,July,Tuesday,low salary
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,0,2019-01-03,0,15,2008,1,7,January,Monday,low salary
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,0,2016-02-01,0,2,2011,7,11,July,Monday,low salary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,0,2016-02-01,0,2,2011,7,11,July,Monday,low salary
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,0,2019-01-07,0,15,2012,1,9,January,Monday,low salary
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,4,2019-01-02,0,19,2014,11,10,November,Monday,average Salary
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,0,2019-02-25,0,19,2013,9,30,September,Monday,low salary
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,0,2019-01-25,0,4,2009,7,6,July,Monday,low salary

In [25]:
salary_dict = {
    'Low salary': 0,
    'Average Salary': 1,
    'high Salary': 2
}

df['salary_num'] = df['SalaryLabel'].map(salary_dict)

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
577   NaN
578   NaN
579   NaN
580   NaN
581   NaN
Name: salary_num, Length: 582, dtype: float64

# Split

In [15]:
## split(find, n = index, expand = True/False(Default))

split_salary = df['SalaryLabel'].str.split(' ',n=1 , expand = True)
split_salary

           0       1
0        low  salary
1    average  Salary
2        low  salary
3        low  salary
4        low  salary
..       ...     ...
577      low  salary
578      low  salary
579  average  Salary
580      low  salary
581      low  salary

[582 rows x 2 columns]

In [16]:
df['Salary1'] = split_salary[0]
df['Salary2'] = split_salary[1]

In [17]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Absences,HireYear,HireMonth,HireDay,HireMonthName,HireDayName,SalaryLabel,salary_num,Salary1,Salary2
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,1,2011,7,5,July,Tuesday,low salary,NaN,low,salary
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,17,2015,3,30,March,Monday,average Salary,NaN,average,Salary
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,3,2011,7,5,July,Tuesday,low salary,NaN,low,salary
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,15,2008,1,7,January,Monday,low salary,NaN,low,salary
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,2,2011,7,11,July,Monday,low salary,NaN,low,salary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,2,2011,7,11,July,Monday,low salary,NaN,low,salary
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,15,2012,1,9,January,Monday,low salary,NaN,low,salary
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,19,2014,11,10,November,Monday,average Salary,NaN,average,Salary
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,19,2013,9,30,September,Monday,low salary,NaN,low,salary
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,4,2009,7,6,July,Monday,low salary,NaN,low,salary

In [20]:
df['Employee_Name']

0           Adinolfi, Wilson  K
1      Ait Sidi, Karthikeyan
2             Akinkuolie, Sarah
3                  Alagbe,Trina
4              Anderson, Carol
                 ...
577            Anderson, Carol
578           Anderson, Linda
579             Andreola, Colby
580                 Athwal, Sam
581            Bachiochi, Linda
Name: Employee_Name, Length: 582, dtype: object

In [18]:
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Absences,HireYear,HireMonth,HireDay,HireMonthName,HireDayName,SalaryLabel,salary_num,Salary1,Salary2
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,1,2011,7,5,July,Tuesday,low salary,NaN,low,salary
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,17,2015,3,30,March,Monday,average Salary,NaN,average,Salary
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,3,2011,7,5,July,Tuesday,low salary,NaN,low,salary
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,15,2008,1,7,January,Monday,low salary,NaN,low,salary
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,2,2011,7,11,July,Monday,low salary,NaN,low,salary

In [20]:
last_first = df['Employee_Name'].str.split(',', n =1 ,expand = True )   # here last name is in 0 index
last_first

# remember when u split from comma there will be the whitespace so u need to remvoe that space also

              0                1
0      Adinolfi        Wilson  K
1      Ait Sidi   Karthikeyan
2    Akinkuolie            Sarah
3        Alagbe            Trina
4      Anderson           Carol
..          ...              ...
577    Anderson           Carol
578    Anderson          Linda
579    Andreola            Colby
580      Athwal              Sam
581   Bachiochi            Linda

[582 rows x 2 columns]

In [21]:
first_middle = last_first[1].str.strip().str.split(' ',n=1, expand = True)
first_middle

               0     1
0         Wilson     K
1    Karthikeyan  None
2          Sarah  None
3          Trina  None
4          Carol  None
..           ...   ...
577        Carol  None
578        Linda  None
579        Colby  None
580          Sam  None
581        Linda  None

[582 rows x 2 columns]

In [22]:
df['First_Name'] = first_middle[0]
df['Middle_Name'] = first_middle[1]
df['Last_Name'] = last_first[0]

In [23]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,HireDay,HireMonthName,HireDayName,SalaryLabel,salary_num,Salary1,Salary2,First_Name,Middle_Name,Last_Name
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,5,July,Tuesday,low salary,NaN,low,salary,Wilson,K,Adinolfi
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,30,March,Monday,average Salary,NaN,average,Salary,Karthikeyan,None,Ait Sidi
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,5,July,Tuesday,low salary,NaN,low,salary,Sarah,None,Akinkuolie
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,7,January,Monday,low salary,NaN,low,salary,Trina,None,Alagbe
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,11,July,Monday,low salary,NaN,low,salary,Carol,None,Anderson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,11,July,Monday,low salary,NaN,low,salary,Carol,None,Anderson
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,9,January,Monday,low salary,NaN,low,salary,Linda,None,Anderson
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,10,November,Monday,average Salary,NaN,average,Salary,Colby,None,Andreola
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,30,September,Monday,low salary,NaN,low,salary,Sam,None,Athwal
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,6,July,Monday,low salary,NaN,low,salary,Linda,None,Bachiochi