In [1]:
#GroupByAggregation .......................................................

In [2]:
import numpy as np
import pandas as pd

In [4]:
employees = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace"],
    "department": ["HR", "IT", "HR", "IT", "Finance", "Finance", "IT"],
    "salary": [50000, 70000, 55000, 80000, 60000, 65000, 72000]
}
df = pd.DataFrame(employees)
df

      name department  salary
0    Alice         HR   50000
1      Bob         IT   70000
2  Charlie         HR   55000
3    David         IT   80000
4      Eva    Finance   60000
5    Frank    Finance   65000
6    Grace         IT   72000

In [7]:
r = df.groupby('department')['salary'].sum()
r

department
Finance    125000
HR         105000
IT         222000
Name: salary, dtype: int64

In [10]:
df["category"] = ['A','B','A','C','D','F','G']
df

      name department  salary category
0    Alice         HR   50000        A
1      Bob         IT   70000        B
2  Charlie         HR   55000        A
3    David         IT   80000        C
4      Eva    Finance   60000        D
5    Frank    Finance   65000        F
6    Grace         IT   72000        G

In [13]:
r = df.groupby(['category','department'])['salary'].sum()
r

category  department
A         HR            105000
B         IT             70000
C         IT             80000
D         Finance        60000
F         Finance        65000
G         IT             72000
Name: salary, dtype: int64

In [17]:
mean =df['salary'].mean() # min max count std
print(mean)

64571.42857142857

In [23]:
count = (df["department"] == "IT").sum()
print(count)

3