In [46]:
#pandas built in top of numpy for handling csv and excel file.
#it has 2 concept series and frames

#these are working of series since it is in single column which is 1d column

In [7]:
import pandas as pd
s = pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [10]:
s.dtype

dtype('int64')

In [11]:
s.values

array([10, 20, 30, 40], dtype=int64)

In [12]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [17]:
print(s.name)

Numbers

In [19]:
s.name ="numbers"

In [39]:
s.to_frame()

        numbers
apple        10
banana       20
grapes       30
carrot       40

In [21]:
#indexing
s

10

In [22]:
s[0:2]

0    10
1    20
Name: numbers, dtype: int64

In [23]:
s[2:4]

2    30
3    40
Name: numbers, dtype: int64

In [24]:
#iloc ----> location based indexing 

s.iloc[3]

40

In [27]:
s.iloc[[1,2,3]]

1    20
2    30
3    40
Name: numbers, dtype: int64

In [40]:
index=["apple","banana","grapes","carrot"]
s.index = index
s.to_frame()

        numbers
apple        10
banana       20
grapes       30
carrot       40

In [33]:
#loc ---> label based indexing where start and stop both are included
s["grapes":"carrot"]

grapes    30
carrot    40
Name: numbers, dtype: int64

In [36]:
# working on dictionary
fruit_protein = {
    "Apple": 0.3,
    "Banana": 1.1,
    "Orange": 0.9,
    "Mango": 0.8,
    "Papaya": 0.5,
    "Pineapple": 0.5,
    "Guava": 2.6,
    "Kiwi": 1.1,
    "Watermelon": 0.6,
    "Grapes": 0.7,
    "Strawberry": 0.8,
    "Blueberry": 0.7,
    "Pear": 0.4,
    "Peach": 0.9,
    "Plum": 0.7,
    "Cherry": 1.1,
    "Pomegranate": 1.7,
    "Avocado": 2.0,
    "Dragon Fruit": 1.2,
    "Jackfruit": 1.7
}

s1 = pd.Series( fruit_protein,name="Protein")
print(s1.to_frame())

              Protein
Apple             0.3
Banana            1.1
Orange            0.9
Mango             0.8
Papaya            0.5
Pineapple         0.5
Guava             2.6
Kiwi              1.1
Watermelon        0.6
Grapes            0.7
Strawberry        0.8
Blueberry         0.7
Pear              0.4
Peach             0.9
Plum              0.7
Cherry            1.1
Pomegranate       1.7
Avocado           2.0
Dragon Fruit      1.2
Jackfruit         1.7

In [42]:
#Conditional Selection.......................................................................................................
s1[s1>1]

Banana          1.1
Guava           2.6
Kiwi            1.1
Cherry          1.1
Pomegranate     1.7
Avocado         2.0
Dragon Fruit    1.2
Jackfruit       1.7
Name: Protein, dtype: float64

In [45]:
#logical operator and or not...............................................................................................................
s1[(s1>0.5) & (s1<1)]

Orange        0.9
Mango         0.8
Watermelon    0.6
Grapes        0.7
Strawberry    0.8
Blueberry     0.7
Peach         0.9
Plum          0.7
Name: Protein, dtype: float64

In [47]:
#modifying the series
s1["Mango"] = 2
s1

Apple           0.3
Banana          1.1
Orange          0.9
Mango           2.0
Papaya          0.5
Pineapple       0.5
Guava           2.6
Kiwi            1.1
Watermelon      0.6
Grapes          0.7
Strawberry      0.8
Blueberry       0.7
Pear            0.4
Peach           0.9
Plum            0.7
Cherry          1.1
Pomegranate     1.7
Avocado         2.0
Dragon Fruit    1.2
Jackfruit       1.7
Name: Protein, dtype: float64