In [10]:
# working on the data frames
import pandas as pd

data = {
    "Name": [
        "Ram", "Hari", "Sita", "John", "Alex",
        "Priya", "Asha", "David", "Nabin", "Sophia"
    ],
    
    "Age": [
        22, 25, 24, 30, 28,
        26, 23, 32, 27, 29
    ],
    
    "Department": [
        "IT", "HR", "Finance", "Marketing", "IT",
        "Sales", "HR", "Finance", "Marketing", "IT"
    ],
    
    "Salary": [
        45000, 50000, 55000, 60000, 65000,
        48000, 52000, 70000, 58000, 75000
    ]
}

In [11]:
data

{'Name': ['Ram',
  'Hari',
  'Sita',
  'John',
  'Alex',
  'Priya',
  'Asha',
  'David',
  'Nabin',
  'Sophia'],
 'Age': [22, 25, 24, 30, 28, 26, 23, 32, 27, 29],
 'Department': ['IT',
  'HR',
  'Finance',
  'Marketing',
  'IT',
  'Sales',
  'HR',
  'Finance',
  'Marketing',
  'IT'],
 'Salary': [45000,
  50000,
  55000,
  60000,
  65000,
  48000,
  52000,
  70000,
  58000,
  75000]}

In [12]:
#changing dic to dataframe
df = pd.DataFrame(data)
df

     Name  Age Department  Salary
0     Ram   22         IT   45000
1    Hari   25         HR   50000
2    Sita   24    Finance   55000
3    John   30  Marketing   60000
4    Alex   28         IT   65000
5   Priya   26      Sales   48000
6    Asha   23         HR   52000
7   David   32    Finance   70000
8   Nabin   27  Marketing   58000
9  Sophia   29         IT   75000

In [13]:
#printing first 2 row
df.head(2)

   Name  Age Department  Salary
0   Ram   22         IT   45000
1  Hari   25         HR   50000

In [14]:
#printing last 3 row
df.tail(3)

     Name  Age Department  Salary
7   David   32    Finance   70000
8   Nabin   27  Marketing   58000
9  Sophia   29         IT   75000

In [15]:
#loc and iloc
df.iloc[1:3,:2] # row ,column

   Name  Age
1  Hari   25
2  Sita   24

In [16]:
df.loc[1:3,["Age","Department"]]

   Age Department
1   25         HR
2   24    Finance
3   30  Marketing

In [17]:
#fetching single column in frame
df[["Age"]]

   Age
0   22
1   25
2   24
3   30
4   28
5   26
6   23
7   32
8   27
9   29

In [19]:
#remove the column
df.drop("Age",axis =1 ) # ''', inplace =True ''' axis = 0 mean row gone , axis = 1 means col gone and if u want to work on orginanl else false which is default

     Name Department  Salary
0     Ram         IT   45000
1    Hari         HR   50000
2    Sita    Finance   55000
3    John  Marketing   60000
4    Alex         IT   65000
5   Priya      Sales   48000
6    Asha         HR   52000
7   David    Finance   70000
8   Nabin  Marketing   58000
9  Sophia         IT   75000

In [20]:
#check the details of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     object
 1   Age         10 non-null     int64
 2   Department  10 non-null     object
 3   Salary      10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

In [21]:
#describe the dataset of float
df.describe()

             Age        Salary
count  10.000000     10.000000
mean   26.600000  57800.000000
std     3.204164   9795.690663
min    22.000000  45000.000000
25%    24.250000  50500.000000
50%    26.500000  56500.000000
75%    28.750000  63750.000000
max    32.000000  75000.000000

In [22]:
#broacasting in pandas
df["Salary"] = df["Salary"]+5000
df["Salary"].to_frame()

   Salary
0   50000
1   55000
2   60000
3   65000
4   70000
5   53000
6   57000
7   75000
8   63000
9   80000

In [23]:
#Renaming the column
df.rename(columns = {"Department":"Dept"},inplace =True)
df

     Name  Age       Dept  Salary
0     Ram   22         IT   50000
1    Hari   25         HR   55000
2    Sita   24    Finance   60000
3    John   30  Marketing   65000
4    Alex   28         IT   70000
5   Priya   26      Sales   53000
6    Asha   23         HR   57000
7   David   32    Finance   75000
8   Nabin   27  Marketing   63000
9  Sophia   29         IT   80000

In [24]:
#finding the unique value 
df["Name"].unique()

array(['Ram', 'Hari', 'Sita', 'John', 'Alex', 'Priya', 'Asha', 'David',
       'Nabin', 'Sophia'], dtype=object)

In [25]:
#checking number of repeted col value.
df["Dept"].value_counts()

Dept
IT           3
HR           2
Finance      2
Marketing    2
Sales        1
Name: count, dtype: int64

In [26]:
df["Increased_sal"] = df["Salary"]*10
df

     Name  Age       Dept  Salary  Increased_sal
0     Ram   22         IT   50000         500000
1    Hari   25         HR   55000         550000
2    Sita   24    Finance   60000         600000
3    John   30  Marketing   65000         650000
4    Alex   28         IT   70000         700000
5   Priya   26      Sales   53000         530000
6    Asha   23         HR   57000         570000
7   David   32    Finance   75000         750000
8   Nabin   27  Marketing   63000         630000
9  Sophia   29         IT   80000         800000

In [27]:
#Data Cleaning.............................................................

#dropping all the null value
df.dropna()
df

     Name  Age       Dept  Salary  Increased_sal
0     Ram   22         IT   50000         500000
1    Hari   25         HR   55000         550000
2    Sita   24    Finance   60000         600000
3    John   30  Marketing   65000         650000
4    Alex   28         IT   70000         700000
5   Priya   26      Sales   53000         530000
6    Asha   23         HR   57000         570000
7   David   32    Finance   75000         750000
8   Nabin   27  Marketing   63000         630000
9  Sophia   29         IT   80000         800000

In [28]:
# drop if any row that had any null value .
df.dropna(how = "any")

     Name  Age       Dept  Salary  Increased_sal
0     Ram   22         IT   50000         500000
1    Hari   25         HR   55000         550000
2    Sita   24    Finance   60000         600000
3    John   30  Marketing   65000         650000
4    Alex   28         IT   70000         700000
5   Priya   26      Sales   53000         530000
6    Asha   23         HR   57000         570000
7   David   32    Finance   75000         750000
8   Nabin   27  Marketing   63000         630000
9  Sophia   29         IT   80000         800000

In [29]:
# drop if all the value that have null then drop
df.dropna(how = "all")

     Name  Age       Dept  Salary  Increased_sal
0     Ram   22         IT   50000         500000
1    Hari   25         HR   55000         550000
2    Sita   24    Finance   60000         600000
3    John   30  Marketing   65000         650000
4    Alex   28         IT   70000         700000
5   Priya   26      Sales   53000         530000
6    Asha   23         HR   57000         570000
7   David   32    Finance   75000         750000
8   Nabin   27  Marketing   63000         630000
9  Sophia   29         IT   80000         800000

In [30]:
#fill the missing value
df["Salary"].fillna(df["Salary"].median())

0    50000
1    55000
2    60000
3    65000
4    70000
5    53000
6    57000
7    75000
8    63000
9    80000
Name: Salary, dtype: int64

In [34]:
df["Age"] = df["Age"].fillna(method="ffill")
df["Age"].to_frame()

   Age
0   22
1   25
2   24
3   30
4   28
5   26
6   23
7   32
8   27
9   29

In [38]:
#change the name sophia to sita
df["Name"]=df["Name"].replace("Sophia","Sita")
df["Name"].to_frame()

    Name
0    Ram
1   Hari
2   Sita
3   John
4   Alex
5  Priya
6   Asha
7  David
8  Nabin
9   Sita

In [39]:
#dealing with duplicate
df_dup = df[df.duplicated(keep="last")]
df_dup

Empty DataFrame
Columns: [Name, Age, Dept, Salary, Increased_sal]
Index: []

In [40]:
#dealing with invalid values

df["increased_salary"] = df["Promoted Salary"].apply(lamba x:x/10 if x> 650000 else x)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3698193349.py, line 3)